### ISSUE TITLE
weather.png not a directory

### ISSUE THREAD

**Issue by simon-mueller** [scar45/conky_solar_burn#1] opened 2016-08-27 15:16 UTC
Hi, when using your .conkyrc i get the following error message:

`cp: target '/home/simon/.cache/weather.png' is not a directory`

The pictures are showing fine and all (since i installed conky-all), but the error message is annoying. Can you fix it?

**Comment by scar45** [comment] 2016-08-27 16:06
Could possible that the weather URL isn't working for the city you entered, and the `weather.xml/.png` files aren't being created -- if your city name contains any spaces, try replacing them with `%20` -- unfortunately that's about the only thing I can think of. You may also want to test the URL in a browser to see if you get your expected result back in XML. Hope that helps!

**Comment by ManuRS** [comment] 2016-08-27 17:35
The problem is real, I have the solution, take a look at the pull request :)
Also there was a problem that you get the image of the next day 

EDIT: no all the awk need the increment, but by error i change all in the pull 

EDIT2: now i think is ok. The problem is some list return 10 elements (like temperatures or day names) but others return 11 (descriptions o image code) because they have diferent values for the current day in general and for the particular moment of the day

**Comment by scar45** [comment] 2016-08-27 20:42
@simon-mueller -- Please test the latest version #3 as I have merged @manurs commit. I would also love to know if the `%20` fix works for you if you have spaces in your city name. Thanks!

**Closed as completed** 2016-08-30 18:25 UTC
